apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: myapp-deploy
  template:
    metadata:
      labels:
        app: myapp-deploy
    spec:
      containers:
      - name: myapp-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["sh", "-c", "echo Deployment is running. Message: $APP_MESSAGE. Token: $API_TOKEN; sleep 3600"]
        env:
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: app-message
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: api-token